import { GimmicksOverviewSetting } from './overview.types';

export const gimmicksOverViewSettings: GimmicksOverviewSetting[] = [
  {
    goToPage: '/gimmicks/weather',
    header: 'gimmicks.menu.weather',
    icon: true,
    iconClasses: 'fa-cloud text-amber-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'NestJS API',
      'OpenStreetMap API',
      'Geonames API',
      'OpenMeteo API',
      'GeoLocation',
      'Chart.js',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 245,
    green: 158,
    blue: 11,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/map',
    header: 'gimmicks.menu.map',
    icon: true,
    iconClasses: 'fa-map text-yellow-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'Google Maps API',
      'gimmicks.overview.searchTypeahead',
      'Drag and drop',
      'gimmicks.overview.table',
      'gimmicks.overview.resizable',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 234,
    green: 179,
    blue: 8,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/calendar',
    header: 'gimmicks.menu.calendar',
    icon: true,
    iconClasses: 'fa-calendar text-red-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'MyMemory API',
      'Wikimedia API',
      'SVG',
      'Popup modal',
      'Bottom drawer',
      'gimmicks.overview.scratchCard',
      'gimmicks.overview.print',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 239,
    green: 68,
    blue: 68,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/guestbook',
    header: 'gimmicks.menu.guestbook',
    icon: true,
    iconClasses: 'fa-book text-green-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.overview.youtubePlayer',
      'Popup modal',
      'gimmicks.overview.editor',
      'gimmicks.overview.fileStorage',
      'NestJS API',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 34,
    green: 197,
    blue: 94,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/charts',
    header: 'gimmicks.menu.charts',
    icon: true,
    iconClasses: 'fa-chart-simple text-purple-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.overview.charts',
      'gimmicks.overview.imageManipulation',
      'gimmicks.overview.fileUpload',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 168,
    green: 85,
    blue: 247,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/countries',
    header: 'gimmicks.menu.countries',
    icon: false,
    iconClasses: '',
    imageSrc: '',
    emoji: '🌍',
    elements: [
      'World Bank API',
      'Wikipedia API',
      'Leaflet',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 20,
    green: 184,
    blue: 166,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/auth/main',
    header: 'gimmicks.menu.jokes',
    icon: true,
    iconClasses: 'fa-face-smile text-orange-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.jokes.auth',
      'NestJS API',
      'gimmicks.jokes.stripe',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 249,
    green: 115,
    blue: 22,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/games',
    header: 'gimmicks.menu.games',
    icon: false,
    iconClasses: '',
    imageSrc: 'assets/svg/tic-tac-toe.svg',
    emoji: '',
    elements: [
      'NestJS API',
      'Websocket',
      'Firebase'
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 236,
    green: 72,
    blue: 153,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/recipes',
    header: 'gimmicks.menu.recipes',
    icon: false,
    iconClasses: '',
    imageSrc: '',
    emoji: '🍲',
    elements: [
      'NgRx',
      'NestJS API',
      'MyMemory API',
      'gimmicks.overview.imageManipulation',
      'gimmicks.overview.fileUpload',
      'gimmicks.overview.print',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 251,
    green: 113,
    blue: 133,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/movies',
    header: 'gimmicks.menu.movies',
    icon: false,
    iconClasses: '',
    imageSrc: '',
    emoji: '🎬',
    elements: [
      'gimmicks.overview.youtubePlayer',
      'TMDB API',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 250,
    green: 204,
    blue: 21,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/imagegen',
    header: 'gimmicks.menu.imagegen',
    icon: true,
    iconClasses: 'fa-wand-magic-sparkles text-blue-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'Cloudflare Workers AI',
    ],
    showDescription: true,
    playAudio: false,
    red: 59,
    green: 130,
    blue: 246,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/telegram',
    header: 'Telegram',
    icon: true,
    iconClasses: 'fab fa-telegram-plane text-blue-400',
    imageSrc: '',
    emoji: '🎬',
    elements: [
      'Telegram API',
      'NestJS API',
      'Websocket',
      // 'Responsive design',
      // 'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 0,
    green:0,
    blue: 85,
    opacity: 128,
    hex: '',
  },
];
