import { GimmicksOverviewSetting } from './overview.types';

export const gimmicksOverViewSettings: GimmicksOverviewSetting[] = [
  {
    goToPage: '/gimmicks/weather',
    header: 'gimmicks.menu.weather',
    icon: true,
    iconClasses: 'fa-cloud text-amber-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'Nest.js API',
      'OpenStreetMap API',
      'Geonames API',
      'OpenMeteo API',
      'GeoLocation',
      'Chart.js',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 180,
    green: 83,
    blue: 9,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/map',
    header: 'gimmicks.menu.map',
    icon: true,
    iconClasses: 'fa-map text-yellow-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'Google Maps API',
      'gimmicks.overview.searchTypeahead',
      'Drag and drop',
      'gimmicks.overview.table',
      'gimmicks.overview.resizable',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 250,
    green: 204,
    blue: 21,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/calendar',
    header: 'gimmicks.menu.calendar',
    icon: true,
    iconClasses: 'fa-calendar text-red-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'MyMemory API',
      'Wikimedia API',
      'SVG',
      'Popup modal',
      'Bottom drawer',
      'gimmicks.overview.scratchCard',
      'gimmicks.overview.print',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 248,
    green: 113,
    blue: 113,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/guestbook',
    header: 'gimmicks.menu.guestbook',
    icon: true,
    iconClasses: 'fa-book text-green-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.overview.youtubePlayer',
      'Popup modal',
      'gimmicks.overview.editor',
      'gimmicks.overview.fileStorage',
      'Nest.js API',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 74,
    green: 222,
    blue: 128,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/charts',
    header: 'gimmicks.menu.charts',
    icon: true,
    iconClasses: 'fa-chart-simple text-orange-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.overview.charts',
      'gimmicks.overview.imageManipulation',
      'gimmicks.overview.fileUpload',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 251,
    green: 146,
    blue: 60,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/auth/main',
    header: 'gimmicks.menu.jokes',
    icon: true,
    iconClasses: 'fa-face-smile text-violet-100',
    imageSrc: '',
    emoji: '',
    elements: [
      'gimmicks.jokes.auth',
      'Nest.js API',
      'gimmicks.jokes.stripe',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 34,
    green: 211,
    blue: 238,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/games',
    header: 'gimmicks.menu.games',
    icon: false,
    iconClasses: '',
    imageSrc: 'assets/svg/tic-tac-toe.svg',
    emoji: '',
    elements: [
      'Nest.js API',
      'Websocket',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 165,
    green: 42,
    blue: 42,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/recipes',
    header: 'gimmicks.menu.recipes',
    icon: false,
    iconClasses: '',
    imageSrc: '',
    emoji: '🍲',
    elements: [
      'NgRx',
      'Nest.js API',
      'MyMemory API',
      'gimmicks.overview.imageManipulation',
      'gimmicks.overview.fileUpload',
      'gimmicks.overview.print',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 30,
    green: 58,
    blue: 138,
    opacity: 128,
    hex: '',
  },
  {
    goToPage: '/gimmicks/movies',
    header: 'gimmicks.menu.movies',
    icon: false,
    iconClasses: '',
    imageSrc: '',
    emoji: '🎬',
    elements: [
      'gimmicks.overview.youtubePlayer',
      'TMDB API',
      'Responsive design',
      'gimmicks.differentLanguages',
    ],
    showDescription: true,
    playAudio: false,
    red: 255,
    green: 255,
    blue: 0,
    opacity: 128,
    hex: '',
  },
];
