name: Deploy to Server

on:
  push:
    branches:
      - new  # Passe den Branch an, den du deployen willst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log Current Date
        run: echo "📅 Aktuelles Datum $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Create environment file
        run: |
          cat > src/environments/environment.prod.ts << 'EOF'
          const ip = 'benjaminmilcic.site';

          export const environment = {
            stripePublishableKey: '${{ secrets.STRIPE_PUBLISHABLE_KEY }}',
            stripe: {
              createApi: `https://${ip}:3000/stripe`,
              returnUrl: `https://auf-zu-neuen-welten.de`,
            },
            guestbook: {
              getAllPostsApi: `https://${ip}:3000/guestbook`,
              addPostApi: `https://${ip}:3000/guestbook`,
              filesUrl: `https://${ip}:3000/files`,
            },
            contact: {
              form2mailApi: `https://${ip}:3000/form2email`,
            },
            auth: {
              getJokesFile: `https://${ip}:3000/auth/jokes`,
              login: `https://${ip}:3000/auth/login`,
              signup: `https://${ip}:3000/auth/signup`,
              elevenLabsKey: '${{ secrets.ELEVENLABS_API_KEY }}',

            },
            moorhuhn: {
              moorhuhnApi: `https://${ip}:3000/moorhuhn`,
            },
            error: {
              errorMessageApi: `https://${ip}:3000/error2email`,
            },
            yahtzeeGame: {
              webSocketsUrl: `https://${ip}:3000/yahtzee-game`,
            },
            geoLocation: {
              reverseGeoCodeApi: `https://${ip}:3000/geolocation/reverse-geocode`,
              geoCodeApi: `https://${ip}:3000/geolocation/geocode`,
              citiesApi: `https://${ip}:3000/geolocation/cities`,
            },
            googleLogin: {
              loginApi: `https://${ip}:3000/auth/google`,
            },
            recipes: {
              recipesApi: `https://${ip}:3000/recipes`,
              filesUrl: `https://${ip}:3000/files`,
              translationEmail: 'benjamin.milcic@gmail.com',
            },
            analytics: {
               sendData: `https://${ip}:3000/analytics/visitor-data`,
            },
            geoapify: {
               apiKey: '${{ secrets.GEOAPIFY_API_KEY }}',
            },
            maptiler: {
              apiKey: '${{ secrets.MAPTILER_API_KEY }}', 
            },
            telegram: {
              apiUrl: `https://${ip}:3000/telegram`,
              webSocketsUrl: `https://${ip}:3000/telegramws`,
            },
            tmdb: {
              apiKey: '${{ secrets.TMDB_API_KEY }}',
            },
            googleMaps: {
              apiKey: '${{ secrets.GOOGLE_MAPS_API_KEY }}',
            },
            tinymce: {
              apiKey: '${{ secrets.TINYMCE_API_KEY }}',
            },
            imagegen: {
              workerUrl: 'https://little-sky-725e.benjamin-milcic.workers.dev/',
            },
            search: {
              embedUrl: 'https://little-sky-725e.benjamin-milcic.workers.dev/embed',
            },
            production: true,
            version: new Date().getTime(),
          };
          EOF

      - name: Build (optional)
        run: |
          npm install --force
          npm run build  # Falls du Angular oder ein anderes Build-Tool nutzt

      - name: List build output
        run: |
          echo "Checking build output structure:"
          ls -R dist/ || echo "dist folder not found"

      - name: Zielverzeichnis bereinigen
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            find ~/ -maxdepth 1 -mindepth 1 \
              ! -name '.ssh' \
              ! -name 'api' \
              ! -name 'ckeditor' \
              ! -name '.bash_history' \
              ! -name '.htaccess' \
              -exec rm -rf {} +

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            port: 22
            source: "dist/aznw-routes/*"
            target: "~/"
            strip_components: 2